CREATE TABLE sttgaz.stage_creatio_NavNpsCalcutaion (
	Id VARCHAR,
	CreatedOn TIMESTAMP,
	CreatedById VARCHAR,
	ModifiedOn TIMESTAMP,
	ModifiedById VARCHAR,
	ProcessListeners VARCHAR,
	NavFinalBonusId VARCHAR,
	NavCriterionFive decimal(18,2),
	NavCriterionFour decimal(18,2),
	NavCriterionThree VARCHAR,
	NavCriterionTwo decimal(18,2),
	NavCriterionOne decimal(18,2),
	NavCalculationTypeId VARCHAR,
	NavAccountId VARCHAR,
	NavRegionId VARCHAR,
	NavPollId VARCHAR,
	NavConversationScriptTypeId VARCHAR,
	NavCriterionSix VARCHAR
);
